- hosts: ubuntu-bionic
  become: yes
  tasks:
    - name: installation package  
      apt:
        name: "{{ packages }}" 
        state: installed # valeurs possibles absent, build-dep, installed, latest, present, removed, present
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: ajout GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: mettre les repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: docker-repository

    - name: installation de docker
      apt: 
        name: docker-ce 
        update_cache: yes
        state: present # valeurs possibles absent, build-dep, installed, latest, present, removed, present