- name: Installation package 
  hosts: all
  become: yes
  tasks: 
    - name: install apache2 
      apt: 
        name: apache2 
        update_cache: yes
        state: present # valeurs possibles absent, build-dep, installed, latest, present, removed, present
      
    - name: start apache2
      service:
        name: apache2
        state: started # valeurs possibles reloaded, restarted, started, stopped
